agent_v5_kaggle:
  start: agent_v5_kaggle/start.sh
  dockerfile: agent_v5_kaggle/Dockerfile
  kwargs: {}
  env_vars:
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
    DEBUG: "1"
  privileged: false
