agent_v5_kaggle:
  start: agent_v5_kaggle/start_gpu.sh
  dockerfile: agent_v5_kaggle/Dockerfile
  kwargs: {}
  env_vars:
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    DEBUG: "1"
    MONITOR_GPU: "1"
  privileged: false
