agent_v6_kaggle:
  start: agent_v6_kaggle/start.sh
  dockerfile: agent_v6_kaggle/Dockerfile
  kwargs: {}
  env_vars:
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
    DEBUG: "1"
  privileged: false
